# Build the Go Binary
FROM golang:1.19 as build_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF

# Copy the source into the container
COPY . /service

# Build the service binary
WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the binary in Alpine
FROM alpine:3.14
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=build_sales-api /service /service/service
WORKDIR /service
CMD ["./service"]